version: '3'

services:
  wordpress:
    image: wordpress:php8.0
    ports:
      - 80:8080
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.40
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: